package hat.cap.entityResult;

import lombok.Getter;

@Getter
public enum Code {
    // common
    SUCCESS(1000, "SUCCESS"),
    NO_PERMISSION(1001, "NO_PERMISSION"),
    UNKNOWN_ERROR(1002, "UNKNOWN_ERROR"),

    // user
    USER_HAS_EXIST(2000, "USER_HAS_EXIST"),
    USER_NOT_EXIST(2001, "USER_NOT_EXIST"),
    LOGIN_FAIL(2002, "LOGIN_FAIL"),
    USER_TYPE_WRONG(2003, "USER_TYPE_WRONG"),
    INFORMATION_IS_EMPTY(2004, "INFORMATION_IS_EMPTY"),
    EMAIL_IS_NOT_VALID(2005, "EMAIL_IS_NOT_VALID"),
    PASSWORD_CAN_NOT_EQUAL_USERNAME(2006, "PASSWORD_CAN_NOT_EQUAL_USERNAME"),

    // course
    COURSE_NOT_FOUND(3000, "COURSE_NOT_FOUND"),
    COURSE_HAS_EXIST(3001, "COURSE_HAS_EXIST"),
    COURSE_INSTRUCTOR_NOT_EXIST(3002, "COURSE_INSTRUCTOR_NOT_EXIST"),
    COURSE_IS_FULL(3003, "COURSE_IS_FULL"),
    COURSE_HAS_BEEN_ENROLLED(3004, "COURSE_HAS_BEEN_ENROLLED"),
    COURSE_HAS_NOT_BEEN_ENROLLED(3005, "COURSE_HAS_NOT_BEEN_ENROLLED"),

    // post
    POST_TITLE_IS_EMPTY(4000, "POST_TITLE_IS_EMPTY"),
    POST_NOT_EXIST(4001, "POST_NOT_EXIST"),

    // announcement
    ANNOUNCEMENT_TITLE_IS_EMPTY(5001, "ANNOUNCEMENT_TITLE_IS_EMPTY"),

    // assignment
    ASSIGNMENT_TITLE_IS_EMPTY(6001, "ASSIGNMENT_TITLE_IS_EMPTY"),
    ASSIGNMENT_NOT_EXIST(6002, "ASSIGNMENT_NOT_EXIST"),
    ;


    private final int code;
    private final String message;

    Code(int code, String message) {
        this.code = code;
        this.message = message;
    }


}
